# coding: utf-8

"""
    ORR API Documentation

    The main ORR documentation is located at: https://mmisw.org/orrdoc/  __Please note__: - The ORR API is approaching a stable version but is still work in progress.   Please [let us know](https://github.com/mmisw/mmiorr-docs/issues) if you have any   questions or suggestions.  - Besides the documentation itself, this page lets you directly exercise and test the API.   Click on any operation header below to learn more details about it, and see a \"Try it out\" button.  - You can click on the \"Authorize\" button at the top right of this page   (or the `!` icon under the particular operation)   to retrieve an authentication token corresponding to your ORR instance credentials (username and password).   Once authorized, the authentication token will be automatically included in the corresponding request.   You will be able to not only perform the basic `GET` operations,   but also see expanded responses according to your access privileges   as well as perform other operations.  - The \"Try it out\" button will also show the corresponding API call that you can submit   from the command line using [`curl`](https://curl.haxx.se/).  - This API includes administrative operations related with the triple store.   The SPARQL endpoint itself   (located at `https://mmisw.org/sparql` for the MMI ORR instance)   is not described here.   (General SPARQL information can be found [here](https://en.wikipedia.org/wiki/SPARQL),   and regarding the current service used by the ORR to support the SPARQL interface   [here](http://franz.com/agraph/support/documentation/current/http-protocol.html).)  - Actual requests from this page are against the specific endpoint at   `https://mmisw.org/ont`. 

    OpenAPI spec version: v0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.ontology_api import OntologyApi


class TestOntologyApi(unittest.TestCase):
    """ OntologyApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.ontology_api.OntologyApi()

    def tearDown(self):
        pass

    def test_add_ont(self):
        """
        Test case for add_ont

        Registers a brand new ontology
        """
        pass

    def test_add_term(self):
        """
        Test case for add_term

        Adds a term to an existing ORR vocabulary
        """
        pass

    def test_delete_ont(self):
        """
        Test case for delete_ont

        Deletes a particular version or a whole ontology entry
        """
        pass

    def test_ont_get(self):
        """
        Test case for ont_get

        Gets information about registered ontologies or terms
        """
        pass

    def test_update_ont(self):
        """
        Test case for update_ont

        Updates a given ontology version or adds a new version
        """
        pass

    def test_upload_ont(self):
        """
        Test case for upload_ont

        Uploads an ontology file for subsequent registration
        """
        pass


if __name__ == '__main__':
    unittest.main()
