build: false
    
environment:
    matrix:
        - PYTHON_VERSION: 2.7
          MINICONDA: C:\Miniconda
     
branches:
  only:
    - master

install:
  - "set PATH=%MINICONDA%;%MINICONDA%\\Scripts;%PATH%"
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - "conda create -q -n test-environment python=%PYTHON_VERSION% pip setuptools wheel nose"
  - activate test-environment
  - pip install coverage
  - python setup.py install
  - pip install -U pip setuptools wheel
  - python setup.py -q develop



test_script:
   - nosetests 
